# Generated by Django 4.2.2 on 2023-06-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=100)),
                ('agencia_origem', models.IntegerField()),
                ('conta_origem', models.CharField(max_length=7)),
                ('banco_destino', models.CharField(max_length=100)),
                ('agencia_destino', models.IntegerField()),
                ('conta_destino', models.CharField(max_length=7)),
                ('valor_da_transação', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_e_hora_da_transacao', models.DateTimeField()),
            ],
        ),
    ]
